<?php
// --- AUTOGENERATED ---
// database configuration
$db_name = 'ethimox';			// database name
$db_hostname = '127.0.0.1';	// database host (usually 'localhost')
$db_username = 'root';	// database username
$db_password = 'password';		// database password
$db_prefix = 'qe_';		// database password
$qe_hash_key = 'Iw_l6nPoQv}fnBTgbL$SGSte%Rz[,]5H';	// hash key
$qe_admin_folder = 'admin';			// admin folder, eg: https://www.myweb.tld/[admin], you can change it to improve security

// To rename your administrator ACP folder:
// 1. rename the folder /admin to something, eg /myadmin
// 2. enter the new name to $qe_admin_folder above, eg: 'myadmin'
// 3. save, you are done!
?>